### ISSUE TITLE
sabyenc causes segfault in sabnzbd

### ISSUE THREAD

**Issue by MrBuddyCasino** [sabnzbd/sabyenc#10]
This happened after upgrading to 2.3.1-33.
I'm using a Synology 2013j, which is ARMv7 with 512MB of RAM.
Deleting temporary files can fix this, but soon the issue occurs again.

Opening in the core in GDB says:
```warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `/usr/local/sabnzbd/env/bin/python /usr/local/sabnzbd/share/SABnzbd/SABnzbd.py -'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  decode_buffer_usenet (crc_correct=<synthetic pointer>, filename_out=0x4e145730, num_bytes_reserved=0, output_buffer=0x427ed001 <error: Cannot access memory at address 0x427ed001>,
    Py_input_list=0x41d454b8, crc=<optimized out>, crc_yenc=<optimized out>) at src/sabyenc.c:318
318	src/sabyenc.c: No such file or directory.
```

**Comment by Safihre** [comment]
`318	src/sabyenc.c: No such file or directory.`
Is that normal?

Since this and later version has had 200.000+ downloads and no report of this problem, I am leaning towards thinking this might actually be a problem with your memory or the specific Synology version?
Maybe you can try the update Synology package that has been in test for a while?
https://github.com/Safihre/spksrc/releases/tag/sabnzbd-all

**Comment by MrBuddyCasino** [comment]
Installed sabnzbd_armada370-6.1_2.3.2-34.spk, that seems to have fixed it. Thanks for making this btw, its a very useful piece of software.
