### ISSUE TITLE
CPU features not detected

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabyenc#32]
@animetosho I ran SABnzbd with the new sabyenc3 module on my Intel NUC with a Pentium N3700.
The runtime detection only reports SSE2 available, but this CPU should have more than that.
How can I debug this best?
![image](https://user-images.githubusercontent.com/5703454/158078507-00d989a5-f540-4293-929c-ec4ee1eaffd4.png)

**Comment by animetosho** [comment]
N3700 would be Airmont (14nm Silvermont), so that behaviour [is deliberate](https://github.com/sabnzbd/sabyenc/blob/0ca5eec7628b10a1949522b85384b1bb21a33528/src/yencode/platform.cc#L106-L110).

**Comment by Safihre** [comment]
Oh wow, how did you find out about all these specific limitations of specific platforms? User. Reports or there is some page that lists them?

**Comment by animetosho** [comment]
Benchmarking is usually the best option for making a judgement (and I did test this on a Silvermont CPU).

But having a rough understanding of what's slow on various CPU microarchitectures helps with instruction selection. There's various listings for those around, such as Intel/AMD's optimization guides, [Agner's instruction tables](https://www.agner.org/optimize/instruction_tables.ods), [uops.info](https://uops.info/) and [InstLatX64](http://users.atw.hu/instlatx64/).  
For example, the [`PSHUFB` instruction](https://uops.info/html-instr/PSHUFB_XMM_XMM.html) usually executes in 1 cycle on most CPUs, however they take 5 or 6 cycles on Bonnell/Airmont, which means you want to avoid using them in some cases\*.

\* the instruction is mostly used in two places - special character matching (finding = \0 \r etc characters), and character compaction (removing newlines, escape characters etc). Even if slow, it's actually still worth using `PSHUFB` for character compaction on Bonnell/Silvermont because the SSE2 emulation is slower. However, because special character matching occurs more often, using `PSHUFB` there ends up making the whole thing slower.  
This does mean that you could be more selective and compile something more optimised for the CPU (i.e. only use it for character compaction) - in fact, such microarchitectural-specific tuning [exists in the code](https://github.com/sabnzbd/sabyenc/blob/0ca5eec7628b10a1949522b85384b1bb21a33528/src/yencode/decoder_sse_base.h#L115-L124). But to avoid having too many compilation units (making the compiled code unnecessarily large), I only specify four targets (generic SSE2, SSSE3, AVX, AVX2 targets) which seem to cater well for most cases.  
If you wanted to maximise performance, you could search the codebase for `__tune_` and generate relevant compilation units for those (as well as add the [other supported ISA levels](https://github.com/sabnzbd/sabyenc/blob/0ca5eec7628b10a1949522b85384b1bb21a33528/src/yencode/common.h#L211-L220)). Most of the time, the differences are too small to be worth it.

**Comment by Safihre** [comment]
Thanks for that detailed explanation!
You really invested a lot into this. Just one last time my offer to send you a donation for all this work you put into it 💯  
It can be either through PayPal or crypto, whichever you prefer, just let me know (safihre@sabnzbd.org). If not, I also understand and won't mention it again 🙂
